#index:
#    path: /
#    controller: App\Controller\DefaultController::index

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc


# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"
