index:
   path: /
   controller: App\Controller\AppController::indexAction

# Prueba para Oauth
redirect-uri-example:
   path: /redirect-uri-example
   controller: App\Controller\AppController::indexAction

editar:
   path: /oauth/v2/auth/editar/{id}
   controller: App\Controller\AppController::editarAction
   requirements:
        id: \d+

borrar:
   path: /oauth/v2/auth/borrar/{id}
   controller: App\Controller\AppController::borrarAction
   requirements:
        id: \d+        

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

# Añadir esto si se va a usar Authorization
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

listado:
   path: /oauth/v2/auth/listado
   controller: App\Controller\AppController::listadoAction  
# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"
